import { Link, router } from '@inertiajs/react';
import { Search } from 'lucide-react';
import { useState } from 'react';
import Pagination from '../../../components/admin/Pagination';
import AdminLayout from '../../../layouts/AdminLayout';

export default function AttemptsIndex({ attempts, filters }) {
    const [form, setForm] = useState({ search: filters.search ?? '', difficulty: filters.difficulty ?? '', status: filters.status ?? '', from: filters.from ?? '', to: filters.to ?? '' });
    const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
    const submit = (event) => { event.preventDefault(); router.get('/admin/attempts', form, { preserveState: true, replace: true }); };
    return <AdminLayout title="Quiz attempts"><form onSubmit={submit} className="admin-filter-bar"><label className="relative grow"><Search className="absolute left-3 top-3.5 text-slate-600" size={16} /><input className="field pl-10" value={form.search} onChange={(e) => update('search', e.target.value)} placeholder="Player name or email" /></label><select className="field sm:w-40" value={form.difficulty} onChange={(e) => update('difficulty', e.target.value)}><option value="">Difficulty</option><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select><select className="field sm:w-40" value={form.status} onChange={(e) => update('status', e.target.value)}><option value="">Status</option><option value="started">Started</option><option value="completed">Completed</option><option value="abandoned">Abandoned</option></select><input type="date" className="field sm:w-40" value={form.from} onChange={(e) => update('from', e.target.value)} /><input type="date" className="field sm:w-40" value={form.to} onChange={(e) => update('to', e.target.value)} /><button className="button-primary">Filter</button></form><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>ID</th><th>Player</th><th>Difficulty</th><th>Status</th><th>Score</th><th>Accuracy</th><th>Started</th></tr></thead><tbody>{attempts.data.map((attempt) => <tr key={attempt.id}><td><Link href={`/admin/attempts/${attempt.id}`} className="text-link">#{attempt.id}</Link></td><td>{attempt.user?.username ?? 'Deleted user'}</td><td className="uppercase">{attempt.difficulty}</td><td>{attempt.status}</td><td>{attempt.correct_answers}/{attempt.question_count}</td><td>{attempt.accuracy}%</td><td>{new Date(attempt.started_at).toLocaleString()}</td></tr>)}{!attempts.data.length && <tr><td colSpan="7" className="py-12 text-center text-slate-500">No attempts match these filters.</td></tr>}</tbody></table></div><Pagination links={attempts.links} /></AdminLayout>;
}
